### ISSUE TITLE
Improve exception when data is pickled

### ISSUE THREAD

**Issue by Cronan** [manahl/NArctic#56]
The following exception occurs when data is pickled.

> 08:20:59 - Async: System.AggregateException: One or more errors occurred. ---> System.Collections.Generic.KeyNotFoundException: Element 'up_to' not found.
>    at MongoDB.Bson.BsonDocument.get_Item(String name)
>    at NArctic.Arctic.<ReadAsync>d__17.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()

**Comment by Cronan** [comment]
No support for pickles, but a better exception is required.
